# Generated by Django 4.2.6 on 2023-12-07 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashview", "0002_remove_feedback_totalvote_feedbacknew"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="vote",
            name="feedback",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="user",
        ),
        migrations.AlterField(
            model_name="comment",
            name="feedback",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dashview.feedbacknew"
            ),
        ),
        migrations.DeleteModel(
            name="Feedback",
        ),
        migrations.DeleteModel(
            name="Vote",
        ),
    ]
