# Generated by Django 4.2.6 on 2023-10-05 15:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teles", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Employee",
            new_name="Agent",
        ),
    ]
