# Generated by Django 4.2.6 on 2023-11-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teles', '0002_rename_employee_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
